# This file defines the URL patterns for the todo_app.
# When a user requests a URL, Django's URL dispatcher uses these patterns
# to determine which view function or class-based view should handle the request.

# This file will be included in the main project's urls.py (project/urls.py).

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TodoItemViewSet, index  # Import the ViewSet and the index view

# Create a router for DRF ViewSets.
# DefaultRouter automatically creates URL patterns for standard actions (list, create, retrieve, update, destroy).
router = DefaultRouter()

# Register the TodoItemViewSet with the router.
# 'todos' will be the base URL prefix for the API endpoints related to TodoItem.
# For example:
#   /api/todos/ (GET for list, POST for create)
#   /api/todos/{id}/ (GET for retrieve, PUT for update, DELETE for destroy)
router.register(r"todos", TodoItemViewSet)

# Define the URL patterns for the app.
urlpatterns = [
    # This pattern includes all URLs generated by the DRF router.
    # These will be API endpoints (e.g., /api/todos/).
    path("api/", include(router.urls)),
    # This pattern maps the root URL of the app (e.g., /) to the 'index' view.
    # This view (defined in views.py) will serve the main HTML page for the frontend.
    # The name 'index' can be used to refer to this URL pattern in templates or other parts of Django.
    path("", index, name="index"),
]
